# Generated by Django 3.1.4 on 2020-12-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=300)),
                ('twitter_link', models.URLField(max_length=100)),
                ('linkedin_link', models.URLField(max_length=100)),
                ('instagram_link', models.URLField(max_length=100)),
                ('github_link', models.URLField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
